# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hY3z-7iUmvgQGMVZZ8loykEyBclE8ViN
"""

a = 23
b = 245
a =+ b
print (a)

a = 23
b = 245
a // b

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 75 ** 45